version: '3.8'

services:
  postgres:
    container_name: postgres
    image: 'postgres:14.8-alpine'
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: stm_task
    restart: unless-stopped

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    expose:
      - "6369"